{
  "hash": "2b1b030298f51eb30bacd438ade8d9ad",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tópico 1\"\nauthor: \"Richard Pardes-Espinosa\"\ndata: \"2024-07-01\"\nformat: html\neditor: visual\neditor_options: \n  chunk_output_type: inline\ntoc: true\nnumber-sections: true\ncode-fold: show\ncode-summary: \"ver código\"\n---\n\n\n## Cargar librerías  \n\nPara el análisis se utilizó las librerías tidyverse y ggplot2. Estas librerías permiten manipular con facilidad la información y la obtención de gráficos de excelente calidad.   \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(ggplot2)\n```\n:::\n\n\n## Datos\nLa data fue previamente elaborada por el PhD. Emerson del Ponte, professor de de Fitopatología de la UFV. Los datos corresponden a las calificaciones obtenidas en dos exámenes, realizadas a estudiantes de posgrado que cursan la disciplina FIP 606. La tabla se caracteriza por presentar una columna que corresponde al factor (prova) con sus prespectivos niveles (sabatina 1 y 2) y dos columnas que pertenecen a las variables pontos y nota. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- tibble::tribble(\n          ~prova, ~pontos, ~nota,\n              1L,     10L,  71.4,\n              1L,     13L,  92.9,\n              1L,     12L,  85.7,\n              1L,      6L,  42.9,\n              1L,     14L,   100,\n              1L,     12L,  85.7,\n              1L,     14L,   100,\n              1L,      8L,  57.1,\n              1L,     14L,   100,\n              1L,     10L,  71.4,\n              1L,     10L,  71.4,\n              1L,     13L,  92.9,\n              1L,      9L,  64.3,\n              1L,     14L,   100,\n              1L,      9L,  64.3,\n              1L,     14L,   100,\n              1L,     12L,  85.7,\n              1L,     14L,   100,\n              1L,      8L,  57.1,\n              1L,      6L,  42.9,\n              1L,     10L,  71.4,\n              1L,     13L,  92.9,\n              2L,     13L, 81.25,\n              2L,     11L, 68.75,\n              2L,     14L,  87.5,\n              2L,     14L,  87.5,\n              2L,     14L,  87.5,\n              2L,     16L,   100,\n              2L,     16L,   100,\n              2L,     16L,   100,\n              2L,     16L,   100,\n              2L,      7L, 43.75,\n              2L,     11L, 68.75,\n              2L,     13L, 81.25,\n              2L,     14L,  87.5,\n              2L,     16L,   100,\n              2L,     11L, 68.75,\n              2L,      7L, 43.75,\n              2L,     16L,   100,\n              2L,      9L, 56.25,\n              2L,      7L, 43.75,\n              2L,     11L, 68.75,\n              2L,     11L, 68.75,\n              2L,     16L,   100\n          )\n```\n:::\n\n\nLa columna \"prova\" corresponde a los exámenes impartidos en dos momentos, motivo por el cual se definirá como factor con dos niveles. Además, esta columna contiene al número de casos evaluados. \n\n\n## Estadísticos descriptivos (ED) \nLas variables evaluadas fueron sometidos la evaluación de los ED. En general, el promedio obtenido para la variable pontos fue de 11.91 ± 2.99, observandose 6 pontos como mínimos (Min) y 16 pontos como el valor más alto (Max). \n\nPara facilitar la contrucción y calculos de los ED, nos apoyamos de las librerías flextable y moments. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(flextable)\nlibrary(moments)\n\ndf |>\n  summarise(n = sum(!is.na(pontos)), \n            Promedio = mean(pontos),\n            Sd = sd(pontos),\n            Asimetria = skewness(pontos),\n            Kurtosis = kurtosis(pontos),\n            Mínimo = min(pontos),\n            Mediana = median(pontos),\n            Máximo = max(pontos)) |> \n  flextable() %>% \n  colformat_double(digits = 2) |> \n  fontsize(size = 12, part = \"all\") |> \n  autofit() %>% \n  set_caption(\"Estadísticos descriptivos para la variable pontos\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-2290d528{}.cl-225a18e4{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2270ca76{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-22713d80{width:0.471in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713d9e{width:0.998in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713db2{width:0.61in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713db3{width:0.98in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713dbc{width:0.887in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713dc6{width:0.832in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713dd0{width:0.925in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713dda{width:0.869in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713de4{width:0.471in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713dee{width:0.998in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713df8{width:0.61in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713e02{width:0.98in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713e03{width:0.887in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713e0c{width:0.832in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713e16{width:0.925in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22713e20{width:0.869in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-2290d528'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-22713d80\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">n</span></p></th><th class=\"cl-22713d9e\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">Promedio</span></p></th><th class=\"cl-22713db2\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">Sd</span></p></th><th class=\"cl-22713db3\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">Asimetria</span></p></th><th class=\"cl-22713dbc\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">Kurtosis</span></p></th><th class=\"cl-22713dc6\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">Mínimo</span></p></th><th class=\"cl-22713dd0\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">Mediana</span></p></th><th class=\"cl-22713dda\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">Máximo</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22713de4\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">44</span></p></td><td class=\"cl-22713dee\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">11.91</span></p></td><td class=\"cl-22713df8\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">2.99</span></p></td><td class=\"cl-22713e02\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">-0.37</span></p></td><td class=\"cl-22713e03\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">2.12</span></p></td><td class=\"cl-22713e0c\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">6</span></p></td><td class=\"cl-22713e16\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">12.50</span></p></td><td class=\"cl-22713e20\"><p class=\"cl-2270ca76\"><span class=\"cl-225a18e4\">16</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nEn cuanto a la variable notas, el promedio general fue de fue de 79.40 con una desviación (±) de 19.13. Los valores mínimos (Min) y máximos (Max) fluctuaron entre 42.90 a 100. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  summarise(n = sum(!is.na(nota)), \n            Promedio = mean(nota),\n            Sd = sd(nota),\n            Asimetria = skewness(nota),\n            Kurtosis = kurtosis(nota),\n            Mínimo = min(nota),\n            Mediana = median(nota),\n            Máximo = max(nota)) |> \n  flextable() %>% \n  colformat_double(digits = 2) |> \n  fontsize(size = 12, part = \"all\") |> \n  autofit() %>% \n  set_caption(\"Estadísticos descriptivos para la variable nota\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-2366bddc{}.cl-232e28b4{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-234391a4{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-23440bd4{width:0.471in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440bfc{width:0.998in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c06{width:0.702in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c10{width:0.98in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c1a{width:0.887in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c24{width:0.832in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c2e{width:0.925in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c42{width:0.869in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c43{width:0.471in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c4c{width:0.998in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c56{width:0.702in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c6a{width:0.98in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c74{width:0.887in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c7e{width:0.832in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c7f{width:0.925in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-23440c92{width:0.869in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-2366bddc'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-23440bd4\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">n</span></p></th><th class=\"cl-23440bfc\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">Promedio</span></p></th><th class=\"cl-23440c06\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">Sd</span></p></th><th class=\"cl-23440c10\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">Asimetria</span></p></th><th class=\"cl-23440c1a\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">Kurtosis</span></p></th><th class=\"cl-23440c24\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">Mínimo</span></p></th><th class=\"cl-23440c2e\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">Mediana</span></p></th><th class=\"cl-23440c42\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">Máximo</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-23440c43\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">44</span></p></td><td class=\"cl-23440c4c\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">79.40</span></p></td><td class=\"cl-23440c56\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">19.13</span></p></td><td class=\"cl-23440c6a\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">-0.53</span></p></td><td class=\"cl-23440c74\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">2.10</span></p></td><td class=\"cl-23440c7e\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">42.90</span></p></td><td class=\"cl-23440c7f\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">85.70</span></p></td><td class=\"cl-23440c92\"><p class=\"cl-234391a4\"><span class=\"cl-232e28b4\">100.00</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nEn cuanto a la asimetría, para las dos variables se registro una tendencia negativa en la campana de Gauss, siendo para la variable pontos y nota de -0.37 y -0.53.\n\n## Supuestos de normalidad\nSe realizó un gráfico de densidad para verificar los supuestos de normalidad.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  ggplot(aes(x = pontos, \n             fill = factor(prova))) + \n  geom_density(alpha = 0.3) + \n  geom_vline(aes(xintercept = mean(pontos)), \n             color = \"black\", \n             linetype = \"dashed\", \n             linewidth = 1) +\n  theme_bw() +\n  labs(x = \"Puntos\",\n       y = \"Densidad\", \n       fill = \"Prueba\") +\n  scale_x_continuous(expand = c(0,0), \n                     limits = c(0,20)) + \n  scale_y_continuous(expand = c(0,0)) +\n  theme(axis.title = element_text(size = 12, color = \"black\")) +\n  theme(axis.text.x = element_text(size = 10, color = \"black\")) +\n  theme(axis.text.y = element_text(size = 10, color = \"black\")) +\n  theme(legend.position = c(0.08, 0.9),\n        legend.background = element_rect(color = NULL),\n        legend.text = element_text(size = 10), \n        legend.title = element_text(size = 10, face = NULL))\n```\n\n::: {.cell-output-display}\n![](20_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nEn la Figura 1, se presenta la distribución de las calificaciones obtenidas por los estudiantes del posgrado de Fitopatología, UFV. Se observa que el examen 1 y 2 presentan una distribución ligeramente simétrica, con picos ligaramente pronunciados que sobresalen hacia la izquierda del punto de tendencia central.   \n\nLa Figura proporciona información sobre los casos, que parece seguir una distribución no paramétrica. La distribución podría deberse a la naturaleza categórica de los datos. Tal vez, una transformación a la raíz(x) podría ayudar a normalizar la distribución de los datos para luego realizar la prueba de t-student con la finalidad de determinar el rendimiento de los alumnos a través del tiempo.   \n\nCabe destacar que, el rendimiento en el segundo examen fue más uniforme en comparación con la primera. En términos de aprendizaje, podría hipotetizar que los alumnos de la UFV han mejorado su aprendizaje para la segunda prueba; ya que, al parece la primera prueba parece agrupar a los alumnos en dos clases, uno con notas altas y otra con notas bajas, respectivamente. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Para la variable nota\ndf |> \n  ggplot(aes(x = nota, fill = factor(prova))) + \n  geom_density(alpha = 0.3) + \n  geom_vline(aes(xintercept = mean(nota)), \n             color = \"black\", linetype = \"dashed\", linewidth = 1) +\n  theme_bw() +\n  labs(x = \"Nota (%)\",\n       y = \"Densidad\", \n       fill = \"Prueba\") +\n  scale_x_continuous(expand = c(0,0), \n                     limits = c(0,150)) + \n  scale_y_continuous(expand = c(0,0)) +\n  theme(axis.title = element_text(size = 12, color = \"black\")) +\n  theme(axis.text.x = element_text(size = 10, color = \"black\")) +\n  theme(axis.text.y = element_text(size = 10, color = \"black\")) +\n  theme(legend.position = c(0.08, 0.9),\n        legend.background = element_rect(color = NULL),\n        legend.text = element_text(size = 10), \n        legend.title = element_text(size = 10, face = NULL))\n```\n\n::: {.cell-output-display}\n![](20_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nInteresantemente, cuando se grafica con la variable \"nota\", las curva de densidad de la Figura 2 se supersonen en comparación con las curvas de densidad de la Figura 1. Esta observación se debe a que en la Figura 2, las pruebas fueron evaluadas a la misma escala de puntuación, es decir, para la variable \"pontos\" y \"notas\" el rango de observaciones varian de 0 a 14 o 16 y de 0 a 100, respectivamente. \n\nEs esperado las similitudes entre la Figura 1 y 2. Sin embargo, en la Figura 2, se observa que las diferencias se acentuan más entre los casos observados, formando grupos dentro de cada examen.\n\nA continuación, se realizará una prueba se evaluará la normalidad de la distribución de los datos observados bajo un nivel de significancia de p-value de 0.05 (p>0.05). \n\n\n::: {.cell}\n\n```{.r .cell-code}\nattach(df)\nshapiro.test(pontos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  pontos\nW = 0.93263, p-value = 0.01291\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(nota)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  nota\nW = 0.87972, p-value = 0.0002742\n```\n\n\n:::\n:::\n\n\nSegún la prueba de Shapiro-Wilk para evaluar la normalidad de los datos, para la variable \"pontos\" y \"nota\" se obtuvo un p-value de 0.01291 y 0.0002742, respectivamente. La prueba reafirma lo observado en la Figura 1 y 2. \n\n## Boxplot \n\nPosteriormente, se realizó una figura boxplot sólo con la variable nota, ya que esta variable esta cuantificada en un valor porcentual a los puntajes obtenidos por cada estudiante, es decir, el rango de evaluación para todos los casos se encuentra en la misma escala porcentual (%). A continuación se muestra la Figura. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  ggplot(aes(prova, nota, fill = factor(prova))) +\n  stat_boxplot(geom = \"errorbar\", \n               width = 0.15) +\n  geom_boxplot(outlier.shape = NA,\n               color = \"black\",\n               size = 0.5) + \n  geom_jitter(color = \"black\",\n               size = 2) +\n  theme_classic() +\n  labs(x = \"Pruebas\",\n       y = \"Nota (%)\",\n       fill = \"Tratamientos\") +\n  scale_x_continuous(breaks = c(1,2)) + \n  scale_y_continuous(limits = c(40,140),\n                     breaks = c(40,80,120)) +\n  theme(axis.title = element_text(size = 20, color = \"red\")) +\n  theme(axis.text.x = element_text(size = 15, color = \"blue\")) +\n  theme(axis.text.y = element_text(size = 15, color = \"green\")) +\n  theme(legend.position = c(0.15, 0.87),\n        legend.background = element_rect(color = \"black\"),\n        legend.text = element_text(size = 15), \n        legend.title = element_text(size = 15))\n```\n\n::: {.cell-output-display}\n![](20_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nDe la Figura 3, observamos similaridad entre las observaciones de los casos para la prueba 1 y 2. Problablemente, no exista diferencias significativas entre los tratamientos evaluados. \n\n",
    "supporting": [
      "20_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}